### ISSUE TITLE
Library Usage

### ISSUE THREAD

**Issue by marler8997** [hdorio/hwzip.zig#2]
I'd like to try out and possibly use this zip library in my "zigup" tool: https://github.com/marler8997/zigup

I'm currently using zarc but it's slow and the maintainer seems to be too busy to be able to maintain it.

This project just seems to be missing a few things to be able to use it as a library, such as making some of the functions public like `extract_file` and maybe creating an "index file" which provides a single module that exposes all the modules with public members, i.e.

`hufman.zig`
```zig
pub const deflate = @import("deflate.zig");
pub const huffman = @import("huffman.zig");
//...
```

**Comment by hdorio** [comment]
> I'd like to [...] use this zip library

I'm sorry but hwzip.zig is not meant to be used as a library, it is merely educational.
Its purpose is to serve as code examples for the following [article](https://www.hanshq.net/zip.html).

> I'm currently using zarc but it's slow

hwzip.zig is also slow.

Currently zarc [uses the old](https://github.com/SuperAuguste/zarc/blob/2a8fd27baa781b9de821b1b4e0b89283413054b8/src/formats/zip.zig#L733) slow deflate decompressor (inflateStream) from the Zig standard library.
If you update zarc to use the [new one](https://github.com/ziglang/zig/pull/10552) (deflate.decompressor) zarc might become faster.

> the maintainer seems to be too busy to be able to maintain it

I don't see any LICENSE file in the zipup repository, but my guess is that you will use a compatible license to the MIT license. So you could just copy zip.zig (and the zarc/LICENSE.md) from the zarc project and modify zip.zig to replace inflateStream.
Just for the meantime for someone to release a decent Zig library to read zip archives.

**Comment by marler8997** [comment]
Thanks for all the info that was very helpful. I'll consider your suggestions.
